# Generated by Django 3.2.3 on 2021-06-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qnadataset',
            name='answer',
            field=models.TextField(max_length=4800),
        ),
    ]
