# Generated by Django 3.2.3 on 2021-06-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_qnadataset_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QnADataSet',
        ),
    ]
