# Generated by Django 3.2.3 on 2021-06-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QnADataSet', '0002_greetingsdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyConversationDataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.CharField(max_length=4800)),
                ('responses', models.TextField(max_length=4800)),
            ],
        ),
    ]
